### ISSUE TITLE
AttributeError: 'getField'

### ISSUE THREAD

**Issue by almeidajeff** [collective/sc.photogallery#43]
Ao habilitar a opção 'Habilitar o download de imagens globalmente?' na view @@photogallery-settings
a visão padrão do Galeria de Fotos passa a apresentar o erro

```pytb
2018-01-17T15:54:39 ERROR Zope.SiteErrorLog 1516211679.290.0209499556037 http://localhost:8071/idg/fotos/view
Traceback (innermost last):
  Module ZPublisher.Publish, line 138, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 48, in call_object
  Module plone.autoform.view, line 47, in __call__
  Module plone.autoform.view, line 38, in render
  Module Products.Five.browser.pagetemplatefile, line 125, in __call__
  Module Products.Five.browser.pagetemplatefile, line 59, in __call__
  Module zope.pagetemplate.pagetemplate, line 132, in pt_render
  Module five.pt.engine, line 98, in __call__
  Module z3c.pt.pagetemplate, line 163, in render
  Module chameleon.zpt.template, line 258, in render
  Module chameleon.template, line 191, in render
  Module chameleon.template, line 171, in render
  Module f92b056c7068eae0e2696b461c44419a, line 1188, in render
  Module f43252458e82836fcda0db389c371b5d, line 1393, in render_master
  Module f43252458e82836fcda0db389c371b5d, line 560, in render_content
  Module f92b056c7068eae0e2696b461c44419a, line 1012, in __fill_content_core
  Module sc.photogallery.browser.view, line 67, in img_size
AttributeError: 'getField'

 Expression: "python:view.img_size(item)"
 Filename:   ... .0b1-py2.7.egg/sc/photogallery/browser/templates/view.pt
 Location:   (line 103: col 57)
 Source:     ... pan tal:replace="python:view.img_size(item)" i18n:name="img_ ...
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
 Expression: "nocall:context/getField"
 Filename:   <string>
 Location:   (line 0: col 0)
 Expression: "nocall:context/getField"
 Filename:   <string>
 Location:   (line 0: col 0)
 - Expression: "nocall:context/getField"
 - Filename:   <string>
 - Location:   (line 0: col 0)
 - Expression: "nocall:context/getField"
 - Filename:   <string>
 - Location:   (line 0: col 0)
 - Arguments:  repeat: {...} (0)
               template: <ViewPageTemplateFile - at 0x7fe405bbcdd0>
               views: <ViewMapper - at 0x7fe405ac1b90>
               modules: <instance - at 0x7fe41b3913b0>
               args: <tuple - at 0x7fe42e81b050>
               here: <ImplicitAcquisitionWrapper fotos at 0x7fe4079acf50>
               user: <ImplicitAcquisitionWrapper - at 0x7fe4079acd70>
               loop: {...} (3)
               nothing: <NoneType - at 0x7fe42e634f80>
               container: <ImplicitAcquisitionWrapper fotos at 0x7fe4079acf50>
request: <instance - at 0x7fe405fe09e0>
               wrapped_repeat: <SafeMapping - at 0x7fe405a87838>
               traverse_subpath: <list - at 0x7fe405fe0cb0>
               default: <object - at 0x7fe42e7f1570>
               context: <ImplicitAcquisitionWrapper fotos at 0x7fe4079acf50>
               view: <SimpleViewClass from /home/jefferson.almeida/Projetos/idg-2.0/portal.buildout/eggs/sc.photogallery-1.0b1-py2.7.egg/sc/photogallery/browser/templates/view.pt view at 0x7fe40584b550>
               translate: <function translate at 0x7fe405a84050>
               root: <ImplicitAcquisitionWrapper Zope at 0x7fe415f55370>
               options: {...} (0)
               target_language: pt_BR
```

### Informações adicionais

Portal Padrão 2.0a2
Plone 4.3.15 (4317)
CMF 2.2.10
Zope 2.13.26
Python 2.7.10 (default, Jun 20 2016, 14:45:40) [GCC 5.3.1 20160406 (Red Hat 5.3.1-6)]
PIL 3.3.0 (Pillow)

**Comment by hvelarde** [comment]
@almeidajeff tu consegue editar e colar o traceback completo ai acima?

**Comment by almeidajeff** [comment]
Segue @hvelarde 

`2018-01-17T15:54:39 ERROR Zope.SiteErrorLog 1516211679.290.0209499556037 http://localhost:8071/idg/fotos/view
Traceback (innermost last):
  Module ZPublisher.Publish, line 138, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 48, in call_object
  Module plone.autoform.view, line 47, in __call__
  Module plone.autoform.view, line 38, in render
  Module Products.Five.browser.pagetemplatefile, line 125, in __call__
  Module Products.Five.browser.pagetemplatefile, line 59, in __call__
  Module zope.pagetemplate.pagetemplate, line 132, in pt_render
  Module five.pt.engine, line 98, in __call__
  Module z3c.pt.pagetemplate, line 163, in render
  Module chameleon.zpt.template, line 258, in render
  Module chameleon.template, line 191, in render
  Module chameleon.template, line 171, in render
  Module f92b056c7068eae0e2696b461c44419a, line 1188, in render
  Module f43252458e82836fcda0db389c371b5d, line 1393, in render_master
  Module f43252458e82836fcda0db389c371b5d, line 560, in render_content
  Module f92b056c7068eae0e2696b461c44419a, line 1012, in __fill_content_core
  Module sc.photogallery.browser.view, line 67, in img_size
AttributeError: 'getField'

 Expression: "python:view.img_size(item)"
 Filename:   ... .0b1-py2.7.egg/sc/photogallery/browser/templates/view.pt
 Location:   (line 103: col 57)
 Source:     ... pan tal:replace="python:view.img_size(item)" i18n:name="img_ ...
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
 Expression: "nocall:context/getField"
 Filename:   <string>
 Location:   (line 0: col 0)
 Expression: "nocall:context/getField"
 Filename:   <string>
 Location:   (line 0: col 0)
 - Expression: "nocall:context/getField"
 - Filename:   <string>
 - Location:   (line 0: col 0)
 - Expression: "nocall:context/getField"
 - Filename:   <string>
 - Location:   (line 0: col 0)
 - Arguments:  repeat: {...} (0)
               template: <ViewPageTemplateFile - at 0x7fe405bbcdd0>
               views: <ViewMapper - at 0x7fe405ac1b90>
               modules: <instance - at 0x7fe41b3913b0>
               args: <tuple - at 0x7fe42e81b050>
               here: <ImplicitAcquisitionWrapper fotos at 0x7fe4079acf50>
               user: <ImplicitAcquisitionWrapper - at 0x7fe4079acd70>
               loop: {...} (3)
               nothing: <NoneType - at 0x7fe42e634f80>
               container: <ImplicitAcquisitionWrapper fotos at 0x7fe4079acf50>
request: <instance - at 0x7fe405fe09e0>
               wrapped_repeat: <SafeMapping - at 0x7fe405a87838>
               traverse_subpath: <list - at 0x7fe405fe0cb0>
               default: <object - at 0x7fe42e7f1570>
               context: <ImplicitAcquisitionWrapper fotos at 0x7fe4079acf50>
               view: <SimpleViewClass from /home/jefferson.almeida/Projetos/idg-2.0/portal.buildout/eggs/sc.photogallery-1.0b1-py2.7.egg/sc/photogallery/browser/templates/view.pt view at 0x7fe40584b550>
               translate: <function translate at 0x7fe405a84050>
               root: <ImplicitAcquisitionWrapper Zope at 0x7fe415f55370>
               options: {...} (0)
               target_language: pt_BR
------

`

**Comment by hvelarde** [comment]
confirmei aqui o problema e achei outros; amanhã vou tentar corrigir.

**Comment by hvelarde** [comment]
I have made a new release, please test it and let me know if it fixes your problem: https://pypi.python.org/pypi/sc.photogallery/1.0b2

**Comment by almeidajeff** [comment]
@hvelarde The problem of the preview was solved, however, with the inclusion of the webpack something went wrong.

Analyzing by browser debug not found files found

```
GET http://localhost:8080/observatorio/portal_css/Sunburst%20Theme/++resource++sc.photogallery/photogallery.css 404 (Not Found)
teste-1.0b2:694 GET http://localhost:8080/observatorio/portal_javascripts/Sunburst%20Theme/++resource++sc.photogallery/photogallery.js 404 (Not Found)
teste-1.0b2:181 GET http://localhost:8080/observatorio/++resource++sc.photogallery/photogallery_icon.png 404 (Not Found)
```

**Comment by hvelarde** [comment]
mmm, my mistake; I'll take a look at this later today.

**Comment by hvelarde** [comment]
fixed! https://pypi.python.org/pypi/sc.photogallery/1.0b3
